version: "3"

services:
  fdv_win_fed_32_s:
    environment:
        - FDV_GIT_REPO
        - FDV_GIT_BRANCH
        - FDV_CLEAN
        - FDV_CMAKE
    build: 
      context: fdv_win_fedora
      args:
         - FED_REL=32

    image:  fdv_win_fed32_i
    container_name: 'fdv_win_fed32_c'
    volumes:
            - win_fed32_v:/home/build/

volumes:
  win_fed32_v:
