# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install pandoc package
        run: |
             sudo apt-get update
             sudo apt-get install pandoc texlive-latex-base texlive-fonts-recommended
           
      - name: Render User Manual to PDF
        run: pandoc USER_MANUAL.md -o USER_MANUAL.pdf "-fmarkdown-implicit_figures -o" --from=markdown --columns=1000 -V geometry:margin=.4in --toc --highlight-style=espresso
        
      - name: Update PDF version in repo
        run: |
             git commit -m "lastest user manual PDF" USER_MANUAL.pdf
             git push
